/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as DianjiRouteImport } from './routes/dianji'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LiuyaoRouteImport } from './routes/liuyao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarriageRouteImport } from './routes/marriage'
import { Route as MeRouteImport } from './routes/me'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NameRouteImport } from './routes/name'
import { Route as NameEvalRouteImport } from './routes/name-eval'
import { Route as NamesRouteImport } from './routes/names'
import { Route as NamingRouteImport } from './routes/naming'
import { Route as PersonalityRouteImport } from './routes/personality'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QimenRouteImport } from './routes/qimen'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RecordsIndexRouteImport } from './routes/records.index'
import { Route as RecordsIdRouteImport } from './routes/records.$id'
import { Route as VoteTokenRouteImport } from './routes/vote.$token'
import { Route as ZodiacIndexRouteImport } from './routes/zodiac/index'
import { Route as ZodiacAnimalIndexRouteImport } from './routes/zodiac/$animal/index'
import { Route as ZodiacAnimalYearRouteImport } from './routes/zodiac/$animal/$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const DianjiRoute = DianjiRouteImport.update({
  id: '/dianji',
  path: '/dianji',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LiuyaoRoute = LiuyaoRouteImport.update({
  id: '/liuyao',
  path: '/liuyao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarriageRoute = MarriageRouteImport.update({
  id: '/marriage',
  path: '/marriage',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRoute = NameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => rootRouteImport,
} as any)
const NameEvalRoute = NameEvalRouteImport.update({
  id: '/name-eval',
  path: '/name-eval',
  getParentRoute: () => rootRouteImport,
} as any)
const NamesRoute = NamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => rootRouteImport,
} as any)
const NamingRoute = NamingRouteImport.update({
  id: '/naming',
  path: '/naming',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalityRoute = PersonalityRouteImport.update({
  id: '/personality',
  path: '/personality',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QimenRoute = QimenRouteImport.update({
  id: '/qimen',
  path: '/qimen',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIdRoute = RecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteTokenRoute = VoteTokenRouteImport.update({
  id: '/vote/$token',
  path: '/vote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ZodiacIndexRoute = ZodiacIndexRouteImport.update({
  id: '/zodiac/',
  path: '/zodiac/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZodiacAnimalIndexRoute = ZodiacAnimalIndexRouteImport.update({
  id: '/zodiac/$animal/',
  path: '/zodiac/$animal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZodiacAnimalYearRoute = ZodiacAnimalYearRouteImport.update({
  id: '/zodiac/$animal/$year',
  path: '/zodiac/$animal/$year',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/coupons': typeof CouponsRoute
  '/dianji': typeof DianjiRoute
  '/help': typeof HelpRoute
  '/invite': typeof InviteRoute
  '/liuyao': typeof LiuyaoRoute
  '/login': typeof LoginRoute
  '/marriage': typeof MarriageRoute
  '/me': typeof MeRoute
  '/messages': typeof MessagesRoute
  '/name': typeof NameRoute
  '/name-eval': typeof NameEvalRoute
  '/names': typeof NamesRoute
  '/naming': typeof NamingRoute
  '/personality': typeof PersonalityRoute
  '/privacy': typeof PrivacyRoute
  '/qimen': typeof QimenRoute
  '/terms': typeof TermsRoute
  '/records/$id': typeof RecordsIdRoute
  '/vote/$token': typeof VoteTokenRoute
  '/records/': typeof RecordsIndexRoute
  '/zodiac/': typeof ZodiacIndexRoute
  '/zodiac/$animal/$year': typeof ZodiacAnimalYearRoute
  '/zodiac/$animal/': typeof ZodiacAnimalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/coupons': typeof CouponsRoute
  '/dianji': typeof DianjiRoute
  '/help': typeof HelpRoute
  '/invite': typeof InviteRoute
  '/liuyao': typeof LiuyaoRoute
  '/login': typeof LoginRoute
  '/marriage': typeof MarriageRoute
  '/me': typeof MeRoute
  '/messages': typeof MessagesRoute
  '/name': typeof NameRoute
  '/name-eval': typeof NameEvalRoute
  '/names': typeof NamesRoute
  '/naming': typeof NamingRoute
  '/personality': typeof PersonalityRoute
  '/privacy': typeof PrivacyRoute
  '/qimen': typeof QimenRoute
  '/terms': typeof TermsRoute
  '/records/$id': typeof RecordsIdRoute
  '/vote/$token': typeof VoteTokenRoute
  '/records': typeof RecordsIndexRoute
  '/zodiac': typeof ZodiacIndexRoute
  '/zodiac/$animal/$year': typeof ZodiacAnimalYearRoute
  '/zodiac/$animal': typeof ZodiacAnimalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/coupons': typeof CouponsRoute
  '/dianji': typeof DianjiRoute
  '/help': typeof HelpRoute
  '/invite': typeof InviteRoute
  '/liuyao': typeof LiuyaoRoute
  '/login': typeof LoginRoute
  '/marriage': typeof MarriageRoute
  '/me': typeof MeRoute
  '/messages': typeof MessagesRoute
  '/name': typeof NameRoute
  '/name-eval': typeof NameEvalRoute
  '/names': typeof NamesRoute
  '/naming': typeof NamingRoute
  '/personality': typeof PersonalityRoute
  '/privacy': typeof PrivacyRoute
  '/qimen': typeof QimenRoute
  '/terms': typeof TermsRoute
  '/records/$id': typeof RecordsIdRoute
  '/vote/$token': typeof VoteTokenRoute
  '/records/': typeof RecordsIndexRoute
  '/zodiac/': typeof ZodiacIndexRoute
  '/zodiac/$animal/$year': typeof ZodiacAnimalYearRoute
  '/zodiac/$animal/': typeof ZodiacAnimalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/coupons'
    | '/dianji'
    | '/help'
    | '/invite'
    | '/liuyao'
    | '/login'
    | '/marriage'
    | '/me'
    | '/messages'
    | '/name'
    | '/name-eval'
    | '/names'
    | '/naming'
    | '/personality'
    | '/privacy'
    | '/qimen'
    | '/terms'
    | '/records/$id'
    | '/vote/$token'
    | '/records/'
    | '/zodiac/'
    | '/zodiac/$animal/$year'
    | '/zodiac/$animal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/coupons'
    | '/dianji'
    | '/help'
    | '/invite'
    | '/liuyao'
    | '/login'
    | '/marriage'
    | '/me'
    | '/messages'
    | '/name'
    | '/name-eval'
    | '/names'
    | '/naming'
    | '/personality'
    | '/privacy'
    | '/qimen'
    | '/terms'
    | '/records/$id'
    | '/vote/$token'
    | '/records'
    | '/zodiac'
    | '/zodiac/$animal/$year'
    | '/zodiac/$animal'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/coupons'
    | '/dianji'
    | '/help'
    | '/invite'
    | '/liuyao'
    | '/login'
    | '/marriage'
    | '/me'
    | '/messages'
    | '/name'
    | '/name-eval'
    | '/names'
    | '/naming'
    | '/personality'
    | '/privacy'
    | '/qimen'
    | '/terms'
    | '/records/$id'
    | '/vote/$token'
    | '/records/'
    | '/zodiac/'
    | '/zodiac/$animal/$year'
    | '/zodiac/$animal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  CouponsRoute: typeof CouponsRoute
  DianjiRoute: typeof DianjiRoute
  HelpRoute: typeof HelpRoute
  InviteRoute: typeof InviteRoute
  LiuyaoRoute: typeof LiuyaoRoute
  LoginRoute: typeof LoginRoute
  MarriageRoute: typeof MarriageRoute
  MeRoute: typeof MeRoute
  MessagesRoute: typeof MessagesRoute
  NameRoute: typeof NameRoute
  NameEvalRoute: typeof NameEvalRoute
  NamesRoute: typeof NamesRoute
  NamingRoute: typeof NamingRoute
  PersonalityRoute: typeof PersonalityRoute
  PrivacyRoute: typeof PrivacyRoute
  QimenRoute: typeof QimenRoute
  TermsRoute: typeof TermsRoute
  RecordsIdRoute: typeof RecordsIdRoute
  VoteTokenRoute: typeof VoteTokenRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
  ZodiacIndexRoute: typeof ZodiacIndexRoute
  ZodiacAnimalYearRoute: typeof ZodiacAnimalYearRoute
  ZodiacAnimalIndexRoute: typeof ZodiacAnimalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dianji': {
      id: '/dianji'
      path: '/dianji'
      fullPath: '/dianji'
      preLoaderRoute: typeof DianjiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liuyao': {
      id: '/liuyao'
      path: '/liuyao'
      fullPath: '/liuyao'
      preLoaderRoute: typeof LiuyaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marriage': {
      id: '/marriage'
      path: '/marriage'
      fullPath: '/marriage'
      preLoaderRoute: typeof MarriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name': {
      id: '/name'
      path: '/name'
      fullPath: '/name'
      preLoaderRoute: typeof NameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name-eval': {
      id: '/name-eval'
      path: '/name-eval'
      fullPath: '/name-eval'
      preLoaderRoute: typeof NameEvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/names': {
      id: '/names'
      path: '/names'
      fullPath: '/names'
      preLoaderRoute: typeof NamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naming': {
      id: '/naming'
      path: '/naming'
      fullPath: '/naming'
      preLoaderRoute: typeof NamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personality': {
      id: '/personality'
      path: '/personality'
      fullPath: '/personality'
      preLoaderRoute: typeof PersonalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qimen': {
      id: '/qimen'
      path: '/qimen'
      fullPath: '/qimen'
      preLoaderRoute: typeof QimenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/': {
      id: '/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$id': {
      id: '/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof RecordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$token': {
      id: '/vote/$token'
      path: '/vote/$token'
      fullPath: '/vote/$token'
      preLoaderRoute: typeof VoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zodiac/': {
      id: '/zodiac/'
      path: '/zodiac'
      fullPath: '/zodiac/'
      preLoaderRoute: typeof ZodiacIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zodiac/$animal/': {
      id: '/zodiac/$animal/'
      path: '/zodiac/$animal'
      fullPath: '/zodiac/$animal/'
      preLoaderRoute: typeof ZodiacAnimalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zodiac/$animal/$year': {
      id: '/zodiac/$animal/$year'
      path: '/zodiac/$animal/$year'
      fullPath: '/zodiac/$animal/$year'
      preLoaderRoute: typeof ZodiacAnimalYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  CouponsRoute: CouponsRoute,
  DianjiRoute: DianjiRoute,
  HelpRoute: HelpRoute,
  InviteRoute: InviteRoute,
  LiuyaoRoute: LiuyaoRoute,
  LoginRoute: LoginRoute,
  MarriageRoute: MarriageRoute,
  MeRoute: MeRoute,
  MessagesRoute: MessagesRoute,
  NameRoute: NameRoute,
  NameEvalRoute: NameEvalRoute,
  NamesRoute: NamesRoute,
  NamingRoute: NamingRoute,
  PersonalityRoute: PersonalityRoute,
  PrivacyRoute: PrivacyRoute,
  QimenRoute: QimenRoute,
  TermsRoute: TermsRoute,
  RecordsIdRoute: RecordsIdRoute,
  VoteTokenRoute: VoteTokenRoute,
  RecordsIndexRoute: RecordsIndexRoute,
  ZodiacIndexRoute: ZodiacIndexRoute,
  ZodiacAnimalYearRoute: ZodiacAnimalYearRoute,
  ZodiacAnimalIndexRoute: ZodiacAnimalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
