/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarriageRouteImport } from './routes/marriage'
import { Route as MeRouteImport } from './routes/me'
import { Route as NamingRouteImport } from './routes/naming'
import { Route as PersonalityRouteImport } from './routes/personality'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RecordsIndexRouteImport } from './routes/records.index'
import { Route as RecordsIdRouteImport } from './routes/records.$id'
import { Route as VoteTokenRouteImport } from './routes/vote.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarriageRoute = MarriageRouteImport.update({
  id: '/marriage',
  path: '/marriage',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NamingRoute = NamingRouteImport.update({
  id: '/naming',
  path: '/naming',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalityRoute = PersonalityRouteImport.update({
  id: '/personality',
  path: '/personality',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIdRoute = RecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteTokenRoute = VoteTokenRouteImport.update({
  id: '/vote/$token',
  path: '/vote/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/login': typeof LoginRoute
  '/marriage': typeof MarriageRoute
  '/me': typeof MeRoute
  '/naming': typeof NamingRoute
  '/personality': typeof PersonalityRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/records/$id': typeof RecordsIdRoute
  '/vote/$token': typeof VoteTokenRoute
  '/records/': typeof RecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/login': typeof LoginRoute
  '/marriage': typeof MarriageRoute
  '/me': typeof MeRoute
  '/naming': typeof NamingRoute
  '/personality': typeof PersonalityRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/records/$id': typeof RecordsIdRoute
  '/vote/$token': typeof VoteTokenRoute
  '/records': typeof RecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/login': typeof LoginRoute
  '/marriage': typeof MarriageRoute
  '/me': typeof MeRoute
  '/naming': typeof NamingRoute
  '/personality': typeof PersonalityRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/records/$id': typeof RecordsIdRoute
  '/vote/$token': typeof VoteTokenRoute
  '/records/': typeof RecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/login'
    | '/marriage'
    | '/me'
    | '/naming'
    | '/personality'
    | '/privacy'
    | '/terms'
    | '/records/$id'
    | '/vote/$token'
    | '/records/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/login'
    | '/marriage'
    | '/me'
    | '/naming'
    | '/personality'
    | '/privacy'
    | '/terms'
    | '/records/$id'
    | '/vote/$token'
    | '/records'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/login'
    | '/marriage'
    | '/me'
    | '/naming'
    | '/personality'
    | '/privacy'
    | '/terms'
    | '/records/$id'
    | '/vote/$token'
    | '/records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  LoginRoute: typeof LoginRoute
  MarriageRoute: typeof MarriageRoute
  MeRoute: typeof MeRoute
  NamingRoute: typeof NamingRoute
  PersonalityRoute: typeof PersonalityRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  RecordsIdRoute: typeof RecordsIdRoute
  VoteTokenRoute: typeof VoteTokenRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marriage': {
      id: '/marriage'
      path: '/marriage'
      fullPath: '/marriage'
      preLoaderRoute: typeof MarriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naming': {
      id: '/naming'
      path: '/naming'
      fullPath: '/naming'
      preLoaderRoute: typeof NamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personality': {
      id: '/personality'
      path: '/personality'
      fullPath: '/personality'
      preLoaderRoute: typeof PersonalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/': {
      id: '/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$id': {
      id: '/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof RecordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$token': {
      id: '/vote/$token'
      path: '/vote/$token'
      fullPath: '/vote/$token'
      preLoaderRoute: typeof VoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  LoginRoute: LoginRoute,
  MarriageRoute: MarriageRoute,
  MeRoute: MeRoute,
  NamingRoute: NamingRoute,
  PersonalityRoute: PersonalityRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  RecordsIdRoute: RecordsIdRoute,
  VoteTokenRoute: VoteTokenRoute,
  RecordsIndexRoute: RecordsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
